[tool.poetry]
name = "django-modeltranslation"
version = "0.14.4"
description = "Translates Django models using a registration approach."
authors = ["Peter Eschler <peschler@gmail.com>"]
maintainers = ["Serhii Tereshchenko <serg.partizan@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6"
django = ">=2.2"
six = "^1.15.0"

[tool.poetry.dev-dependencies]
pdbpp = "^0.10.2"
flake8 = "^3.7.9"
