[tool.poetry]
name = "django-modeltranslation"
version = "0.14.4"
description = "Translates Django models using a registration approach."
authors = ["Peter Eschler <peschler@gmail.com>"]
maintainers = ["Serhii Tereshchenko <serg.partizan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.4"

[tool.poetry.dev-dependencies]
pdbpp = "^0.10.2"
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
